<h1> Soal 1: Pemahaman Tentang Model Evaluasi</h1>

Jawab pertanyaan di bawah ini dengan bahasa masing-masing?

1. Apa perbedaan antara data latih, data validasi, dan data test?
2. Bagaimana cara kita menilai performa suatu model?
3. Apa itu Confusion Matrix? Jelaskan secara lengkap!
4. Apa itu Classification Report dari sklearn?

Jawab: 1. data latih adalah data yang digunakan untuk melatih model, data validasi adalah data yang digunakan utnuk mengukur keakuratan dari model, data test adalah data yang digunakan model untuk melakukan prediksi untuk kemudian diukur keakuratannya
2. dengan menggunakan salah satu dari metrik pada library sklearn
3. suatu metrik untuk mengukur keakuratan data hasil model, menggunakan 4 sistem pembagian hasil yaitu TN,TP,FN,FP 
4. suatu metode untuk melihat nilai dari evaluasi model mulai dari recall, precision, f1 score dll 

---

<h1>Soal 2: Aplikasi Model Evaluasi</h1>

Kali ini kita akan menggunakan data untuk memprediksi kelangsungan hidup pasien yang telah mengalami operasi payudara. Dengan informasi yang dimiliki terkait pasien, kita akan membuat model untuk memprediksi apakah pasien akan bertahan hidup dalam waktu lebih dari 5 tahun atau tidak.

Lebih Lengkapnya kalian bisa membaca informasi tentang dataset di link berikut: https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.names

Buat model Klasifikasi (Model/Algoritma Bebas) untuk memprediksi status pasien dengan ketentuan sebagai berikut:

1. Bagi kedua data ini menjadi data training dan data test dengan test_size=0.25.
3. Pelajar tentang metrics roc_auc_score kemudian buatlah model dan evaluasi dengan menggunakan teknik cross-validation dengan scoring 'roc_auc'. Baca https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html untuk menggunakan metric roc_auc saat cross-validation.
3. Berapa score rata2 dari model dengan teknik cross-validation tersebut?
4. Prediksi data test dengan model yang telah kalian buat!
5. Bagaimana hasil confusion matrix dari hasil prediksi tersebut?
6. Bagaimana classification report dari hasil prediksi tersebut?
5. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status positive?
6. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status negatif?

In [1]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [2]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [3]:
df['survival_status'].value_counts()

1    225
2     81
Name: survival_status, dtype: int64

In [137]:
# Code here
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score

X = df.drop('survival_status', axis=1)
y = df['survival_status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
print('rata-rata skor dengan cross validation',cross_val_score(KNeighborsClassifier(n_neighbors=2),X,y,cv=5,scoring='roc_auc').mean()
)
y_predict = KNeighborsClassifier(n_neighbors=2).fit(X_train,y_train).predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))
print('keakuratan prediksi status negatif',f1_score(y_test, y_predict, pos_label=1))
print('keakuratan prediksi status positif',f1_score(y_test, y_predict, pos_label=2))

rata-rata skor dengan cross validation 0.6156944444444444
[[53  3]
 [19  2]]
              precision    recall  f1-score   support

           1       0.74      0.95      0.83        56
           2       0.40      0.10      0.15        21

    accuracy                           0.71        77
   macro avg       0.57      0.52      0.49        77
weighted avg       0.64      0.71      0.64        77

keakuratan prediksi status negatif 0.828125
keakuratan prediksi status positif 0.15384615384615385


menebak positif cukup baik karena dapat menebak positif 53 dari aslinya 56, sementara menebak negatif sangat buruk karena hanya mendapat 2 dari aslinya 21. dapat dilihat juga dari poin f1 score untuk masing masing 1 dan 2

---

<h1> Soal 3: Pemahaman Tentang Model Selection</h1>

Jelaskan dengan bahasa sendiri!

1. Apa itu Bias dan Variance?
2. Apa itu Overfitting dan Underfitting?
3. Apa yang bisa kita lakukan untuk mengatur kompleksitas dari model?
4. Bagaimana model yang baik?
5. Kapan kita menggunakan GridSearchcv dan kapan menggunakan RandomizedSearchCV?

Jawab: 
1. bias adalah error yang disebabkan karena model yang terlalu simpel dan kurang memperhatikan data training, variance adalah error yang disebabkan karena terlalu berpaku pada data training dan kurang dapat menjeneralisasi data yang belum pernah dilihatnya
2. overfitting adalah ketika model terlalu menangkap detail dan bahkan noise pada data training, cirinya memliki skor bagus pada data training namun skor jelek pada data yang akan diprediksi. underfitting adalah ketika model kurang memperhatikan detail pada data training, sehingga skor pada data training maupun data prediksi sama sama jelek
3. melakukan tuning hyperparameter
4. model yang dpaat mempelajari data training dengan baik dan mampu melakukan generalisasi dari data training tersebut
5. GridSearchCV saat dataset yang dilakukan analisa tidak terlalu besar, RandomizedSearchCV saat data setnya terlalu besar

---

<h1> Soal 4: Aplikasi Model Selection</h1>

1. Bagi kedua data berikut ini menjadi data training dan data test dengan test_size=0.25.
2. Gunakan algoritma KNN sebagai model classifier.
3. Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection.
4. jumlah fold bebas!, gunakan scoring 'roc_auc'
5. Definisikan kombinasi hyperparameter untuk model selection dengan GridSearchCV. kombinasi Hyperparameter bebas, baca lagi dokumentasi KNN di link berikut https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html untuk memahami lagi jenis2 hyperparameter di algorithma KNN.
6. Latih model terhadap data training.
7. Apa hyperparameter terbaik untuk kombinasi hyperparameter kalian?
8. Berapa score validasi terbaik dari model tersebut?
9. Prediksi probabilitasi output dari model yang telah di buat terhadap data test. note : gunakan method .predict_proba() untuk menghasilkan output probabilitas
10. Perhatikan bahwa hasil prediksi ada 2, dimana masing2 adalah nilai probabilitas untuk setiap class label. Ambil nilai probabilitas pasien phositive meninggal dalam waktu kurang dari 5 tahun. note : gunakan bantuan attirubte .classes_ untuk mengetahui urutan label dari hasil prediksi probabilitas.
11. Berapa nilai score roc_auc untuk data test?
12. Apakah model anda termasuk baik, overtting, atau underfitting?
13. Ulangi tahap di atas namun kali ini menggunakan algoritma DecisionTreeClassifier dan kalian bisa menggunakan RandomizedSearchCV apabila process training lama. pelajari algoritma DecisionTreeClassifier di linkberikut: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier
14. Bandingkan scorenya dengan Algoritma KNN, mana yang lebih baik?

Note : Data Science adalah experiment, sangat di dimungkinkan memerlukan beberapa kali percobaan untuk mendapatkan hasil yang terbaik! Happy Coding :)

In [90]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [136]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [124]:
# Code here 306
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import numpy as np
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
model = KNeighborsClassifier()
parameter = {'n_neighbors':np.arange(1,150),'weights':['distance', 'uniform']}
gscv = GridSearchCV(model, param_grid=parameter, scoring='roc_auc',cv=5)
gscv.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149]),
                         'weights': ['distance', 'uniform']},
             s

In [126]:
gscv.best_params_

{'n_neighbors': 38, 'weights': 'uniform'}

In [127]:
gscv.best_score_

0.7104227994227994

In [159]:
probabilitas = KNeighborsClassifier(n_neighbors=38,weights='uniform').fit(X_train,y_train).predict_proba(X_test)
print(probabilitas)

[[0.89473684 0.10526316]
 [0.84210526 0.15789474]
 [0.86842105 0.13157895]
 [0.47368421 0.52631579]
 [0.73684211 0.26315789]
 [0.71052632 0.28947368]
 [0.81578947 0.18421053]
 [0.73684211 0.26315789]
 [0.89473684 0.10526316]
 [0.81578947 0.18421053]
 [0.78947368 0.21052632]
 [0.39473684 0.60526316]
 [0.73684211 0.26315789]
 [0.81578947 0.18421053]
 [0.86842105 0.13157895]
 [0.86842105 0.13157895]
 [0.78947368 0.21052632]
 [0.76315789 0.23684211]
 [0.78947368 0.21052632]
 [0.86842105 0.13157895]
 [0.89473684 0.10526316]
 [0.81578947 0.18421053]
 [0.84210526 0.15789474]
 [0.81578947 0.18421053]
 [0.92105263 0.07894737]
 [0.81578947 0.18421053]
 [0.81578947 0.18421053]
 [0.57894737 0.42105263]
 [0.52631579 0.47368421]
 [0.86842105 0.13157895]
 [0.76315789 0.23684211]
 [0.89473684 0.10526316]
 [0.78947368 0.21052632]
 [0.57894737 0.42105263]
 [0.81578947 0.18421053]
 [0.55263158 0.44736842]
 [0.84210526 0.15789474]
 [0.84210526 0.15789474]
 [0.84210526 0.15789474]
 [0.78947368 0.21052632]


In [160]:
probabilitas[:,1]

array([0.10526316, 0.15789474, 0.13157895, 0.52631579, 0.26315789,
       0.28947368, 0.18421053, 0.26315789, 0.10526316, 0.18421053,
       0.21052632, 0.60526316, 0.26315789, 0.18421053, 0.13157895,
       0.13157895, 0.21052632, 0.23684211, 0.21052632, 0.13157895,
       0.10526316, 0.18421053, 0.15789474, 0.18421053, 0.07894737,
       0.18421053, 0.18421053, 0.42105263, 0.47368421, 0.13157895,
       0.23684211, 0.10526316, 0.21052632, 0.42105263, 0.18421053,
       0.44736842, 0.15789474, 0.15789474, 0.15789474, 0.21052632,
       0.21052632, 0.28947368, 0.15789474, 0.23684211, 0.21052632,
       0.23684211, 0.18421053, 0.13157895, 0.13157895, 0.21052632,
       0.18421053, 0.44736842, 0.13157895, 0.18421053, 0.15789474,
       0.23684211, 0.34210526, 0.57894737, 0.28947368, 0.31578947,
       0.15789474, 0.15789474, 0.18421053, 0.15789474, 0.13157895,
       0.13157895, 0.13157895, 0.18421053, 0.39473684, 0.13157895,
       0.21052632, 0.23684211, 0.10526316, 0.28947368, 0.26315

In [162]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,KNeighborsClassifier(n_neighbors=38,weights='uniform').fit(X_train,y_train).predict(X_test))

0.505952380952381

termasuk buruk, underfitting karena nilai skor baik pada data training maupun data target sama - sama jelek

In [180]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
parameter = {'criterion':['gini','entropy'],'splitter':['best', 'random']}
gscv = GridSearchCV(model, param_grid=parameter, scoring='roc_auc',cv=5)
gscv.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'splitter': ['best', 'random']},
             scoring='roc_auc')

In [181]:
gscv.best_params_

{'criterion': 'entropy', 'splitter': 'best'}

In [182]:
gscv.best_score_

0.6018270944741533

In [184]:
roc_auc_score(y_test,DecisionTreeClassifier(criterion='entropy',splitter='best').fit(X_train,y_train).predict(X_test))

0.5357142857142857

hasil skor yang didapat lebih buruk daripada menggunakan algoritma knn 